### ISSUE TITLE
Need to manually re-authenticate after a few hours

### ISSUE THREAD

**Issue by matthewmueller** [femueller/python-n26#67]
Steps to reproduce:

1) Run an hourly cron to refresh the token
2) After a little while you'll get the following error: `Refresh token not found!`

**Comment by markusressel** [comment]
As stated in #48 I can confirm this is happening. In my single test I had to redo 2FA after approx. 2 hours of using a freshly requested token. For another user (@hajdbo) it took 4 hours to request 2FA again. The server is responding with an error code that it is not able to refresh the token because it does not know about it anymore. We don't know yet why this is happening.

**Comment by hajdbo** [comment]
I checked: 2 hours now.

**Comment by markusressel** [comment]
It would be useful to know if this two hour limit also applies to normal website usage. If that is the case there may be no way to hold up a "session" for longer than 2 hours anymore. If that is the case and the N26 team is not interested in allowing external applications to access their service for longer periods of time (which would be kinda sad) I don't see a way to revive the [home-assistant integration](https://github.com/home-assistant/home-assistant/issues/26637)

**Comment by markusressel** [comment]
I just ran a test on the browser version of N26 using a logged in session in conjunction with an automatic site refresh every 3 minutes. **Sadly the two hour limit also kicks in on the website and forces a user to re-log**. So I guess there are only two options here:
1. figure out how the android app is able to stay logged in for 30 days (although I recon this style of login is only possible with the paired device)
2. ask N26 for a way around this

Since N26 probably introduced this timeout to prevent token hijackers from gaining uncontrolled access to someone else's bank account I don't have high hopes that we will find a solution to this.

**Comment by SoftCreatR** [comment]
And if you refresh too often, further requests are being blocked for at least 30 minutes.

**Comment by femueller** [comment]
I've been also reaching out to n26 and asked if there are plans to offer something like developer tokens that have a longer lifetime.

It would be really nice for this and other n26 related projects that we can gain more transparency about API implementation changes, upcoming features etc.

Currently waiting for their response too :)

**Comment by SoftCreatR** [comment]
Here's the response I've got (tbh, i've expected something else):

```
Hey Sascha, 

Bezüglich deiner Frage habe ich noch ein paar Infos für dich.

Du kannst dein N26 Konto mit token.io verknüpfen.

In dem folgenden Link findest du alle weiteren Infos bezüglich unserer Zusammenarbeit mit  Drittanbietern und wie du diese nutzt.

https://support.n26.com/de-de/erste-schritte/psd2/psd2-and-secure-open-banking 

Falls du noch Fragen hast, melde dich gerne wieder bei uns oder sieh dir unser Support Center unter https://support.n26.com/de-de/erste-schritte 

Sollte dir noch etwas an Verbesserungsvorschlägen einfallen, schick uns eine Mail an ideas@n26.com
```

**Comment by matthewmueller** [comment]
interesting, for the folks that don't speak German:

```
Hey Sasha,

Regarding your question I have some information for you.

You can link your N26 account with token.io.

In the following link you will find all further information regarding our cooperation with third-party providers and how you use them.

https://support.n26.com/de-de/erste-schritte/psd2/psd2-and-secure-open-banking

If you have any questions, feel free to contact us or visit our support center at https://support.n26.com/de-de/erste-schritte

If you have any suggestions for improvement, please send us an e-mail to ideas@n26.com
```

**Comment by SoftCreatR** [comment]
Sorry, just forgot that 😆

**Comment by SoftCreatR** [comment]
Anyone interested in checking this out?

https://n26.docs.token.io/#on-boarding-for-tpps

**Comment by markusressel** [comment]
Even if it were possible, imo the amount of work needed to achieve this extends well beyond the scope of this library. A general purpose library for accessing token.io data would probably be more suitable to this and could probably provide access to many more than just N26 accounts. I don't know if something like this already exists, but I am afraid that such a thing would not be in the interest of "Open Banking" supporters.
