### ISSUE TITLE
Safety Recommendations?

### ISSUE THREAD

**Issue by bimtauer** [femueller/python-n26#74]
Hi there, thanks for the great work!

I'm having some questions regarding password safety that I'm hoping someone can give me some tips on: 

AFAIK, while there is a client instance of the `Api` class, it will reference its respective instance of the `Config` class. Even though the `secret` setting prevents printing the password in plaintext, it's still easily accessible through `client.config.PASSWORD.value` - that means somewhere in the heap memory the password is stored in plaintext. Even if I were to `del client`, I would simply de-reference that memory location and the password is still lying around until the python garbage collection cleans it eventually. 
I'm wondering how severe of a risk this actually is. What would it take for someone to get access to the password this way? 
And if that's an issue how could that be designed to be more secure? Is there some way that ensures the password is only ever in memory for the moment that an API call is made?

**Comment by femueller** [comment]
Thanks for your feedback and concern about this topic.

I think without getting too technical at this point, it should be questioned how critical this actually is, since every n26 transaction needs a second factor confirmation via the n26 phone app.
So the worst thing that could potentially happen is that credentials leak and read access to an account would get acquired.

However, I think long term it sounds like a great idea to have a discussion around it and maybe we will find a solution to even mitigate this risk.

@bimtauer Do you have any prior experience implementing something that could avoid having credentials in plain text in memory?
At some point with most implementations, I could imagine there will be a moment when credentials will become decrypted and plain text in memory, right?

**Comment by markusressel** [comment]
Hi @bimtauer, thx for your interest in the security of this lib.

I would be interested to know what kind of attack vector you have in mind?

Afaik there is no way to access the memory of another process without root access to the system, and if someone gains root access to your system you probably got bigger problems than a malicious process accessing your python process memory. Although python programs run in a virtual machine they do run in their own process, which prevents access of other processes to their memory (unless root).

Although [there are hackish ways](https://stackoverflow.com/questions/728164/securely-erasing-password-in-memory-python) to clear the password from the memory, these do not seem to be in wide use which is probably due to the fact that processes should not be able to look at each others memory in the first place (unless root).

If you have [cold-boot-attack](https://en.wikipedia.org/wiki/Cold_boot_attack) in mind then there really is nothing that we can or should do to prevent this, since only [system-wide memory encryption](https://en.wikipedia.org/wiki/Cold_boot_attack#Effective_countermeasures) is an effective countermeasure.

> I'm wondering how severe of a risk this actually is. What would it take for someone to get access to the password this way?

As mentioned above:
* root
* use this lib inside another lib

If you use and run the python-n26 cli using your normal user account and have not created a service user for n26 (and the configuration file can be read by your user) every other program you run as your user can also access this file. So technically every other program you run with your user would be able to read the configuration file if they know where to look. To prevent this it would be necessary to use a different storage altogether to get the credentials, I guess [keyring](https://pypi.org/project/keyring/) would be an option here as @femueller mentioned, although I have no experience using it whatsoever, so I don't know how well that would translate to Windows users.

> And if that's an issue how could that be designed to be more secure? Is there some way that ensures the password is only ever in memory for the moment that an API call is made?

Currently no code exists to do such a thing.  
If this is something worth implementing it would be good to try and implement this inside of [container-app-conf](https://github.com/markusressel/container-app-conf) which is the library used to read the configuration in python-n26.
